export {
  addMeal,
  addWater,
  buildNutritionInsights,
  calculateNutritionSummary,
  calculateWaterProgress,
  deleteMeal,
  formatNutritionDate,
  getBrazilDateKey as getLocalDateKey,
  getNutritionHistory,
  getNutritionLogs,
  getTodayNutritionLog,
  normalizeMeal,
  normalizeNutritionLog,
  removeWater,
  saveNutritionLog,
  saveNutritionLogs,
  setDailyWaterGoal,
  updateMeal,
  updateNutritionGoals,
  validateMealFields,
  validateNutritionGoals,
} from '../../services/nutritionService'
