export const TUTORIAL_VERSION = 5

export const tutorialRouteFlows = {
  '/': 'dashboard',
  '/dashboard': 'dashboard',
  '/workouts': 'workouts',
  '/exercises': 'workouts',
  '/start-workout': 'workout',
  '/history': 'history',
  '/calendar': 'dashboard',
  '/schedule': 'dashboard',
  '/progress': 'history',
  '/exercise-progress': 'history',
  '/progress-photos': 'history',
  '/muscle-recovery': 'history',
  '/nutrition': 'nutrition',
  '/notifications': 'settings',
  '/profile': 'settings',
  '/settings': 'settings',
  '/goals': 'dashboard',
}

export const tutorialSections = {
  welcome: {
    id: 'welcome',
    order: 1,
    title: 'Boas-vindas',
    shortTitle: 'Início',
    description: 'O mínimo para começar sem cansar.',
  },
  dashboard: {
    id: 'dashboard',
    order: 2,
    title: 'Dashboard',
    shortTitle: 'Dashboard',
    description: 'Resumo do dia e ponto de partida.',
  },
  navigation: {
    id: 'navigation',
    order: 3,
    title: 'Navegação',
    shortTitle: 'Navegação',
    description: 'Como circular pelo app.',
  },
  workouts: {
    id: 'workouts',
    order: 4,
    title: 'Treinos',
    shortTitle: 'Treinos',
    description: 'Criar, editar e iniciar rotinas.',
  },
  workout: {
    id: 'workout',
    order: 5,
    title: 'Treino ativo',
    shortTitle: 'Ativo',
    description: 'Registrar séries sem mexer em treino real durante o tutorial.',
  },
  history: {
    id: 'history',
    order: 6,
    title: 'Histórico',
    shortTitle: 'Histórico',
    description: 'Evolução real após registrar treinos.',
  },
  nutrition: {
    id: 'nutrition',
    order: 7,
    title: 'Nutrição',
    shortTitle: 'Nutrição',
    description: 'Água, refeições e metas.',
  },
  settings: {
    id: 'settings',
    order: 8,
    title: 'Ajuda',
    shortTitle: 'Ajuda',
    description: 'Onde rever o tutorial.',
  },
}

function step({
  id,
  section,
  title,
  description,
  example = '',
  target = '',
  route = '/',
  mode = 'panel',
  dock = 'auto',
  scroll = true,
  requireTarget = false,
  allowInteraction = true,
  canSkip = true,
  fallbackTitle = '',
  fallbackDescription = '',
}) {
  return {
    id,
    section,
    title,
    description,
    example,
    target,
    selector: target,
    route,
    mode,
    presentation: mode === 'highlight' ? 'inline' : 'panel',
    placement: dock,
    dock,
    scroll,
    scrollIntoView: scroll,
    requireTarget,
    requireElement: requireTarget,
    allowInteraction,
    canSkip,
    fallbackTitle,
    fallbackDescription,
  }
}

const quickTourSteps = [
  step({
    id: 'welcome-short',
    section: 'welcome',
    title: 'Bem-vindo ao ForgeFlow',
    description: 'Um tour rápido para entender o básico. Sem dezenas de passos e sem card cobrindo a tela.',
    route: '/',
    mode: 'welcome',
    canSkip: true,
  }),
  step({
    id: 'dashboard-start',
    section: 'dashboard',
    title: 'Seu ponto de partida',
    description: 'O Dashboard mostra o que fazer agora. No começo, ele orienta; depois usa seus treinos reais.',
    target: '[data-tutorial="dashboard-insights"], [data-tutorial="dashboard-hero"]',
    route: '/',
    mode: 'highlight',
    fallbackTitle: 'Dashboard',
    fallbackDescription: 'Quando ainda não há dados, o Dashboard mostra orientações simples para começar.',
  }),
  step({
    id: 'navigation-simple',
    section: 'navigation',
    title: 'Navegação simples',
    description: 'Use a barra inferior para trocar de área. Ela não será destacada para evitar cortes no rodapé do Android.',
    route: '/',
    mode: 'panel',
  }),
  step({
    id: 'workouts-create',
    section: 'workouts',
    title: 'Crie ou inicie treinos',
    description: 'Em Treinos você monta rotinas e inicia uma sessão quando for treinar de verdade.',
    target: '[data-tutorial="create-workout-button"], [data-tutorial="workouts-list"]',
    route: '/workouts',
    mode: 'highlight',
    fallbackTitle: 'Treinos',
    fallbackDescription: 'Se a lista estiver vazia, use o botão de criar treino para montar sua primeira rotina.',
  }),
  step({
    id: 'workout-register-demo',
    section: 'workout',
    title: 'Registre kg e reps',
    description: 'Cada série concluída vira histórico, volume e recorde pessoal. Esta etapa é só uma simulação visual.',
    route: '/',
    mode: 'demo',
  }),
  step({
    id: 'workout-finish-confirmation',
    section: 'workout',
    title: 'Finalize com segurança',
    description: 'Treinos reais pedem confirmação antes de salvar. Assim você evita histórico duplicado ou incompleto.',
    route: '/',
    mode: 'panel',
  }),
  step({
    id: 'history-empty-friendly',
    section: 'history',
    title: 'Histórico e evolução',
    description: 'Gráficos, PRs e histórico aparecem depois dos primeiros treinos. Conta nova pode ficar vazia mesmo.',
    route: '/history',
    mode: 'panel',
  }),
  step({
    id: 'nutrition-start',
    section: 'nutrition',
    title: 'Nutrição rápida',
    description: 'Acompanhe água, refeições e metas sem precisar descer a tela toda.',
    target: '[data-tutorial="nutrition-overview"], [data-tutorial="nutrition-insights"], [data-tutorial="nutrition-water"]',
    route: '/nutrition',
    mode: 'highlight',
    fallbackTitle: 'Nutrição',
    fallbackDescription: 'Use os botões rápidos para registrar água e refeições. Os insights aparecem conforme houver dados.',
  }),
  step({
    id: 'settings-replay',
    section: 'settings',
    title: 'Rever quando quiser',
    description: 'Em Configurações você pode reiniciar o tutorial ou rever partes específicas.',
    target: '[data-tutorial="settings-tutorial"], [data-tutorial="settings-tutorial-card"], [data-tutorial="settings-tutorial-panel"]',
    route: '/settings',
    mode: 'highlight',
    fallbackTitle: 'Tutorial e ajuda',
    fallbackDescription: 'A área de ajuda fica nas Configurações para você rever este guia quando quiser.',
  }),
]

export const tutorialFlows = {
  welcome: {
    id: 'welcome',
    title: 'Tour rápido do ForgeFlow',
    description: 'Tutorial curto, contextual e sem tooltip cobrindo conteúdo.',
    sections: ['welcome', 'dashboard', 'navigation', 'workouts', 'workout', 'history', 'nutrition', 'settings'],
    steps: quickTourSteps,
  },
  dashboard: {
    id: 'dashboard',
    title: 'Tutorial do Dashboard',
    description: tutorialSections.dashboard.description,
    sections: ['dashboard', 'navigation'],
    steps: [quickTourSteps[1], quickTourSteps[2]],
  },
  navigation: {
    id: 'navigation',
    title: 'Tutorial da navegação',
    description: tutorialSections.navigation.description,
    sections: ['navigation'],
    steps: [quickTourSteps[2]],
  },
  workouts: {
    id: 'workouts',
    title: 'Tutorial de Treinos',
    description: tutorialSections.workouts.description,
    sections: ['workouts'],
    steps: [quickTourSteps[3]],
  },
  workout: {
    id: 'workout',
    title: 'Tutorial de Treino ativo',
    description: tutorialSections.workout.description,
    sections: ['workout'],
    steps: [quickTourSteps[4], quickTourSteps[5]],
  },
  history: {
    id: 'history',
    title: 'Tutorial de Histórico',
    description: tutorialSections.history.description,
    sections: ['history'],
    steps: [quickTourSteps[6]],
  },
  progress: {
    id: 'progress',
    title: 'Tutorial de Evolução',
    description: tutorialSections.history.description,
    sections: ['history'],
    steps: [quickTourSteps[6]],
  },
  nutrition: {
    id: 'nutrition',
    title: 'Tutorial de Nutrição',
    description: tutorialSections.nutrition.description,
    sections: ['nutrition'],
    steps: [quickTourSteps[7]],
  },
  notifications: {
    id: 'notifications',
    title: 'Tutorial de Notificações',
    description: 'Como acompanhar avisos importantes sem bagunça.',
    sections: ['settings'],
    steps: [quickTourSteps[8]],
  },
  settings: {
    id: 'settings',
    title: 'Tutorial de Configurações',
    description: tutorialSections.settings.description,
    sections: ['settings'],
    steps: [quickTourSteps[8]],
  },
}

export function getTutorialSteps(flowId = 'welcome') {
  return tutorialFlows[flowId]?.steps || tutorialFlows.welcome.steps
}

export function getTutorialFlow(flowId = 'welcome') {
  return tutorialFlows[flowId] || tutorialFlows.welcome
}

export default tutorialFlows
