export const TUTORIAL_VERSION = 2

export const tutorialRouteFlows = {
  '/': 'dashboard',
  '/dashboard': 'dashboard',
  '/workouts': 'workouts',
  '/exercises': 'exercises',
  '/start-workout': 'workout',
  '/history': 'history',
  '/calendar': 'schedule',
  '/schedule': 'schedule',
  '/progress': 'progress',
  '/exercise-progress': 'progress',
  '/progress-photos': 'photosRecovery',
  '/muscle-recovery': 'photosRecovery',
  '/nutrition': 'nutrition',
  '/notifications': 'notifications',
  '/profile': 'profile',
  '/settings': 'settings',
  '/goals': 'goals',
}

export const tutorialSections = {
  welcome: {
    id: 'welcome',
    order: 1,
    title: 'Boas-vindas',
    shortTitle: 'Início',
    description: 'Entenda a proposta do ForgeFlow e como controlar o guia.',
  },
  dashboard: {
    id: 'dashboard',
    order: 2,
    title: 'Dashboard',
    shortTitle: 'Dashboard',
    description: 'Seu centro de treino, semana, resumo e próxima ação.',
  },
  navigation: {
    id: 'navigation',
    order: 3,
    title: 'Navegação',
    shortTitle: 'Navegação',
    description: 'Header, menu, notificações, instalação e barra inferior.',
  },
  workouts: {
    id: 'workouts',
    order: 4,
    title: 'Treinos',
    shortTitle: 'Treinos',
    description: 'Criar, organizar, editar e iniciar rotinas.',
  },
  workout: {
    id: 'workout',
    order: 5,
    title: 'Treino ativo',
    shortTitle: 'Ativo',
    description: 'Registrar kg, reps, séries, descanso e finalização segura.',
  },
  exercises: {
    id: 'exercises',
    order: 6,
    title: 'Exercícios',
    shortTitle: 'Exercícios',
    description: 'Biblioteca, busca, filtros, detalhes e progresso por exercício.',
  },
  history: {
    id: 'history',
    order: 7,
    title: 'Histórico',
    shortTitle: 'Histórico',
    description: 'Treinos finalizados, volume, PRs e compartilhamento.',
  },
  schedule: {
    id: 'schedule',
    order: 8,
    title: 'Agenda',
    shortTitle: 'Agenda',
    description: 'Semana de treinos, dias de descanso e treino do dia.',
  },
  progress: {
    id: 'progress',
    order: 9,
    title: 'Evolução',
    shortTitle: 'Evolução',
    description: 'Gráficos, filtros, volume, frequência e PRs.',
  },
  photosRecovery: {
    id: 'photosRecovery',
    order: 10,
    title: 'Fotos e recuperação',
    shortTitle: 'Fotos/Recup.',
    description: 'Fotos de progresso, comparação visual e recuperação muscular.',
  },
  nutrition: {
    id: 'nutrition',
    order: 11,
    title: 'Nutrição',
    shortTitle: 'Nutrição',
    description: 'Água, refeições, metas e histórico nutricional.',
  },
  notifications: {
    id: 'notifications',
    order: 12,
    title: 'Notificações',
    shortTitle: 'Notificações',
    description: 'Sino, central, preferências e arquivadas.',
  },
  settings: {
    id: 'settings',
    order: 13,
    title: 'Perfil e Configurações',
    shortTitle: 'Config.',
    description: 'Perfil, tema, cor do app, privacidade e revisão do tutorial.',
  },
  goals: {
    id: 'goals',
    order: 14,
    title: 'Metas',
    shortTitle: 'Metas',
    description: 'Acompanhe objetivos de treino, hábitos e consistência.',
  },
}

function step({
  id,
  section,
  title,
  description,
  example = '',
  target = '',
  route = '/',
  placement = 'auto',
  requireElement = false,
  scrollIntoView = true,
  allowInteraction = false,
  optional = false,
  canSkip = true,
  targetLabel = '',
}) {
  return {
    id,
    section,
    title,
    description,
    example,
    target,
    selector: target,
    route,
    placement,
    requireElement,
    scrollIntoView,
    allowInteraction,
    optional,
    canSkip,
    targetLabel,
  }
}

const welcomeSteps = [
  step({
    id: 'welcome-intro',
    section: 'welcome',
    title: 'Bem-vindo ao ForgeFlow',
    description: 'O ForgeFlow ajuda você a registrar treinos, acompanhar cargas, ver evolução e manter consistência.',
    example: 'Você pode pular qualquer parte e rever depois em Configurações.',
    route: '/',
    placement: 'center',
  }),
  step({
    id: 'welcome-controls',
    section: 'welcome',
    title: 'Você controla o ritmo',
    description: 'Use Voltar, Próximo, Pular etapa, Pular seção ou Rever depois quando quiser.',
    example: 'Seu progresso fica salvo e continua de onde parou.',
    route: '/',
    placement: 'center',
  }),
]

const dashboardSteps = [
  step({
    id: 'dashboard-hero',
    section: 'dashboard',
    title: 'Seu centro de treino',
    description: 'Aqui você acompanha progresso semanal, último treino e o estado geral do app.',
    example: 'Quando você treina, esse topo vira um resumo rápido da sua evolução.',
    target: '[data-tutorial="dashboard-hero"]',
    route: '/',
    placement: 'bottom',
    requireElement: true,
    targetLabel: 'Centro de treino',
  }),
  step({
    id: 'dashboard-active-workout',
    section: 'dashboard',
    title: 'Treino em andamento',
    description: 'Este card aparece quando existe um treino ativo e leva você de volta exatamente de onde parou.',
    example: 'Se não houver treino ativo agora, o guia mostra um aviso amigável e permite continuar.',
    target: '[data-tutorial="dashboard-active-workout"], [data-tutorial="active-workout-mini"]',
    route: '/',
    placement: 'bottom',
    optional: true,
    targetLabel: 'Treino ativo',
  }),
  step({
    id: 'dashboard-week',
    section: 'dashboard',
    title: 'Agenda e semana',
    description: 'A semana mostra treinos feitos, planejados e dias de descanso.',
    example: 'Use isso para enxergar constância sem abrir várias telas.',
    target: '[data-tutorial="dashboard-week"]',
    route: '/',
    placement: 'bottom',
    targetLabel: 'Resumo semanal',
  }),
  step({
    id: 'dashboard-summary',
    section: 'dashboard',
    title: 'Resumo de hoje',
    description: 'Este bloco junta treino planejado, água, nutrição, metas e recuperação.',
    example: 'É a leitura rápida do que mais importa hoje.',
    target: '[data-tutorial="dashboard-summary"]',
    route: '/',
    placement: 'top',
    targetLabel: 'Hoje',
  }),
  step({
    id: 'dashboard-next-action',
    section: 'dashboard',
    title: 'Próxima melhor ação',
    description: 'O ForgeFlow sugere uma ação útil: continuar treino, beber água, revisar recuperação ou abrir uma rotina.',
    example: 'Toque aqui quando não souber qual é o próximo passo.',
    target: '[data-tutorial="dashboard-next-action"]',
    route: '/',
    placement: 'top',
    targetLabel: 'Próxima ação',
  }),
  step({
    id: 'dashboard-today-workout',
    section: 'dashboard',
    title: 'Plano do dia',
    description: 'Quando sua agenda estiver montada, o treino planejado para hoje aparece aqui automaticamente.',
    example: 'Sem agenda, o card leva você para configurar a semana.',
    target: '[data-tutorial="dashboard-today-workout"]',
    route: '/',
    placement: 'top',
    targetLabel: 'Treino de hoje',
  }),
  step({
    id: 'dashboard-recent-history',
    section: 'dashboard',
    title: 'Histórico recente',
    description: 'Os últimos treinos aparecem como atalhos para revisar duração, volume e detalhes.',
    example: 'Depois do primeiro treino salvo, esse espaço fica mais útil.',
    target: '[data-tutorial="dashboard-recent-history"]',
    route: '/',
    placement: 'top',
    targetLabel: 'Últimos treinos',
  }),
]

const navigationSteps = [
  step({
    id: 'navigation-header',
    section: 'navigation',
    title: 'Header do app',
    description: 'O topo concentra menu, identidade do app, instalação e notificações sem tomar espaço do treino.',
    example: 'No APK o header fica estável para não quebrar o scroll.',
    target: '[data-tutorial="app-header"]',
    route: '/',
    placement: 'bottom',
    targetLabel: 'Header',
  }),
  step({
    id: 'navigation-menu',
    section: 'navigation',
    title: 'Menu lateral',
    description: 'Abra o menu para acessar áreas menos frequentes e atalhos extras.',
    example: 'No celular, ele evita deixar todas as funções na tela inicial.',
    target: '[data-tutorial="menu-button"]',
    route: '/',
    placement: 'bottom',
    targetLabel: 'Menu',
  }),
  step({
    id: 'navigation-bell',
    section: 'navigation',
    title: 'Notificações',
    description: 'O sino mostra lembretes de treino, água, metas e alertas importantes.',
    example: 'Toque para ver prévias ou ir para a central completa.',
    target: '[data-tutorial="notification-bell"]',
    route: '/',
    placement: 'bottom',
    targetLabel: 'Sino',
  }),
  step({
    id: 'navigation-install',
    section: 'navigation',
    title: 'Instalar app',
    description: 'Quando disponível na web/PWA, este botão ajuda a instalar o ForgeFlow.',
    example: 'No APK Android ele fica oculto porque o app já está instalado.',
    target: '[data-tutorial="app-install-button"]',
    route: '/',
    placement: 'bottom',
    optional: true,
    targetLabel: 'Instalar',
  }),
  step({
    id: 'navigation-bottom',
    section: 'navigation',
    title: 'Barra inferior',
    description: 'A barra inferior deixa as áreas principais sempre ao alcance do polegar.',
    example: 'Use Início, Treino, Agenda, Evolução e Perfil como atalhos principais.',
    target: '[data-tutorial="bottom-nav"]',
    route: '/',
    placement: 'top',
    requireElement: true,
    targetLabel: 'Navegação',
  }),
]

const workoutsSteps = [
  step({
    id: 'workouts-list',
    section: 'workouts',
    title: 'Onde ficam seus treinos',
    description: 'A lista reúne suas rotinas salvas para editar, duplicar, favoritar ou iniciar.',
    example: 'Cada card mostra exercícios, volume e ações rápidas.',
    target: '[data-tutorial="workouts-list"]',
    route: '/workouts',
    placement: 'top',
    targetLabel: 'Lista de treinos',
  }),
  step({
    id: 'create-workout-button',
    section: 'workouts',
    title: 'Criar novo treino',
    description: 'Use este botão para montar uma rotina com nome, pasta, exercícios e séries.',
    example: 'O novo treino começa com uma série por exercício, sem bagunçar a tela.',
    target: '[data-tutorial="create-workout-button"]',
    route: '/workouts',
    placement: 'bottom',
    targetLabel: 'Novo treino',
  }),
  step({
    id: 'workout-card',
    section: 'workouts',
    title: 'Card de treino',
    description: 'O card concentra iniciar, editar, duplicar e organizar a rotina.',
    example: 'Se ainda não houver treinos, o guia mostra o botão de criação como fallback.',
    target: '[data-tutorial="workout-card"], [data-tutorial="create-workout-button"]',
    route: '/workouts',
    placement: 'top',
    optional: true,
    targetLabel: 'Rotina',
  }),
  step({
    id: 'workout-start-button',
    section: 'workouts',
    title: 'Iniciar treino',
    description: 'Ao iniciar uma rotina, o ForgeFlow abre o treino ativo para registrar séries.',
    example: 'A sessão fica persistida para você voltar depois.',
    target: '[data-tutorial="workout-start-button"], [data-tutorial="workout-card"]',
    route: '/workouts',
    placement: 'top',
    optional: true,
    targetLabel: 'Iniciar',
  }),
  step({
    id: 'workout-folder',
    section: 'workouts',
    title: 'Organização por pasta',
    description: 'Use filtros e pastas para separar Push, Pull, Legs, Upper, Lower ou qualquer divisão.',
    example: 'Isso evita uma lista grande demais quando você tiver muitas rotinas.',
    target: '[data-tutorial="workout-folder"]',
    route: '/workouts',
    placement: 'bottom',
    optional: true,
    targetLabel: 'Pastas',
  }),
]

const workoutSteps = [
  step({
    id: 'active-workout-header',
    section: 'workout',
    title: 'Cabeçalho do treino ativo',
    description: 'Aqui ficam nome do treino, progresso geral e o botão de concluir.',
    example: 'Se for um treino teste, ele aparece marcado como tutorial e não entra no histórico real.',
    target: '[data-tutorial="active-workout-header"]',
    route: '/start-workout',
    placement: 'bottom',
    requireElement: true,
    targetLabel: 'Treino ativo',
  }),
  step({
    id: 'active-workout-timer',
    section: 'workout',
    title: 'Cronômetro e progresso',
    description: 'O timer ajuda a controlar duração, séries feitas e avanço da sessão.',
    example: 'Ele continua contando enquanto a sessão estiver ativa.',
    target: '[data-tutorial="active-workout-timer"]',
    route: '/start-workout',
    placement: 'bottom',
    targetLabel: 'Duração',
  }),
  step({
    id: 'active-exercise-card',
    section: 'workout',
    title: 'Exercício atual',
    description: 'Cada exercício tem seu próprio card com mídia, notas, séries e ações.',
    example: 'Role pela sessão ou use a faixa de exercícios para pular direto.',
    target: '[data-tutorial="active-exercise-card"]',
    route: '/start-workout',
    placement: 'top',
    targetLabel: 'Exercício',
  }),
  step({
    id: 'active-set-row',
    section: 'workout',
    title: 'Linha da série',
    description: 'Cada linha representa uma série. Você pode marcar aquecimento, ver anterior, inserir kg/reps e concluir.',
    example: 'O histórico futuro nasce desses registros.',
    target: '[data-tutorial="active-set-row"]',
    route: '/start-workout',
    placement: 'top',
    targetLabel: 'Série',
  }),
  step({
    id: 'active-set-weight-input',
    section: 'workout',
    title: 'Campo de kg',
    description: 'Digite a carga usada na série. O app usa esse valor para volume, gráficos e PRs.',
    example: 'Pode usar decimal, como 42.5 kg.',
    target: '[data-tutorial="active-set-weight-input"]',
    route: '/start-workout',
    placement: 'top',
    targetLabel: 'Carga',
  }),
  step({
    id: 'active-set-reps-input',
    section: 'workout',
    title: 'Campo de reps',
    description: 'Digite quantas repetições você fez. Sem reps, a série não conta como finalizada válida.',
    example: 'Depois toque em concluir série.',
    target: '[data-tutorial="active-set-reps-input"]',
    route: '/start-workout',
    placement: 'top',
    targetLabel: 'Reps',
  }),
  step({
    id: 'active-set-complete-button',
    section: 'workout',
    title: 'Concluir série',
    description: 'Toque aqui quando terminar. O ForgeFlow salva a série e atualiza o progresso.',
    example: 'Se o descanso automático estiver ativo, o timer começa depois do toque.',
    target: '[data-tutorial="active-set-complete-button"]',
    route: '/start-workout',
    placement: 'top',
    allowInteraction: true,
    targetLabel: 'Concluir',
  }),
  step({
    id: 'active-add-set-button',
    section: 'workout',
    title: 'Adicionar série',
    description: 'Use os botões de série vazia ou aquecimento para adaptar o treino na hora.',
    example: 'Séries extras ficam só nesta sessão, a menos que você edite a rotina depois.',
    target: '[data-tutorial="active-add-set-button"]',
    route: '/start-workout',
    placement: 'top',
    targetLabel: 'Adicionar',
  }),
  step({
    id: 'active-next-exercise',
    section: 'workout',
    title: 'Navegar entre exercícios',
    description: 'Esta faixa permite ir direto para qualquer exercício sem se perder no scroll.',
    example: 'Ótimo para treinos grandes no celular.',
    target: '[data-tutorial="active-next-exercise"]',
    route: '/start-workout',
    placement: 'bottom',
    targetLabel: 'Exercícios',
  }),
  step({
    id: 'active-notes',
    section: 'workout',
    title: 'Observações finais',
    description: 'Use notas para registrar dor, dificuldade, energia ou ajustes do treino.',
    example: 'Essas anotações ajudam a interpretar o histórico depois.',
    target: '[data-tutorial="active-workout-notes"]',
    route: '/start-workout',
    placement: 'top',
    optional: true,
    scrollIntoView: true,
    targetLabel: 'Notas',
  }),
  step({
    id: 'active-finish-workout',
    section: 'workout',
    title: 'Finalizar treino',
    description: 'Ao finalizar, treinos reais vão para o histórico. Treinos de tutorial são descartados com segurança.',
    example: 'O app nunca salva dados fake como treino real.',
    target: '[data-tutorial="active-finish-workout-bottom"], [data-tutorial="active-finish-workout-hero"], [data-tutorial="active-finish-workout-desktop"]',
    route: '/start-workout',
    placement: 'top',
    allowInteraction: true,
    targetLabel: 'Concluir treino',
  }),
]

const exercisesSteps = [
  step({
    id: 'exercise-library',
    section: 'exercises',
    title: 'Biblioteca de exercícios',
    description: 'Aqui ficam exercícios padrão e personalizados para montar seus treinos.',
    example: 'Use detalhes para ver músculos, equipamentos e histórico do exercício.',
    target: '[data-tutorial="exercise-library"]',
    route: '/exercises',
    placement: 'bottom',
    targetLabel: 'Biblioteca',
  }),
  step({
    id: 'exercise-search',
    section: 'exercises',
    title: 'Busca rápida',
    description: 'Pesquise por nome, músculo ou equipamento sem sair da tela.',
    example: 'O teclado fecha com Enter para não travar a rolagem no Android.',
    target: '[data-tutorial="exercise-search"]',
    route: '/exercises',
    placement: 'bottom',
    optional: true,
    targetLabel: 'Busca',
  }),
  step({
    id: 'exercise-filters',
    section: 'exercises',
    title: 'Filtros por músculo',
    description: 'Filtre por grupo muscular, equipamento e favoritos para encontrar rápido.',
    example: 'Ideal quando a biblioteca estiver grande.',
    target: '[data-tutorial="exercise-filters"]',
    route: '/exercises',
    placement: 'bottom',
    optional: true,
    targetLabel: 'Filtros',
  }),
  step({
    id: 'exercise-card',
    section: 'exercises',
    title: 'Card de exercício',
    description: 'O card leva aos detalhes e pode ser usado para montar treinos.',
    example: 'Se não houver cards carregados, você pode pular esta etapa.',
    target: '[data-tutorial="exercise-card"]',
    route: '/exercises',
    placement: 'top',
    optional: true,
    targetLabel: 'Exercício',
  }),
]

const historySteps = [
  step({
    id: 'history-list',
    section: 'history',
    title: 'Lista do histórico',
    description: 'Treinos finalizados aparecem aqui com duração, exercícios, volume e detalhes.',
    example: 'Sem histórico ainda, o app mostra um estado vazio sem quebrar o tutorial.',
    target: '[data-tutorial="history-list"]',
    route: '/history',
    placement: 'bottom',
    targetLabel: 'Histórico',
  }),
  step({
    id: 'history-card',
    section: 'history',
    title: 'Card de treino finalizado',
    description: 'Abra um treino para revisar séries, cargas, reps e observações.',
    example: 'É aqui que você entende o que evoluiu.',
    target: '[data-tutorial="history-card"]',
    route: '/history',
    placement: 'top',
    optional: true,
    targetLabel: 'Treino salvo',
  }),
  step({
    id: 'history-pr',
    section: 'history',
    title: 'Recordes pessoais',
    description: 'PRs mostram quando você superou carga ou volume anteriores.',
    example: 'O histórico mostra o recorde e a referência anterior quando disponível.',
    target: '[data-tutorial="history-pr"]',
    route: '/history',
    placement: 'top',
    optional: true,
    targetLabel: 'PR',
  }),
  step({
    id: 'history-share-button',
    section: 'history',
    title: 'Compartilhar treino',
    description: 'Gere um card visual para salvar ou compartilhar seu treino.',
    example: 'O compartilhamento usa dados do treino finalizado.',
    target: '[data-tutorial="history-share-button"]',
    route: '/history',
    placement: 'top',
    optional: true,
    targetLabel: 'Compartilhar',
  }),
]

const scheduleSteps = [
  step({
    id: 'schedule-week',
    section: 'schedule',
    title: 'Semana de treino',
    description: 'Monte sua agenda de segunda a domingo com treinos e descanso.',
    example: 'Depois disso, o Dashboard passa a sugerir o treino do dia.',
    target: '[data-tutorial="schedule-week"]',
    route: '/schedule',
    placement: 'bottom',
    targetLabel: 'Semana',
  }),
  step({
    id: 'schedule-day',
    section: 'schedule',
    title: 'Dia com treino',
    description: 'Cada dia pode receber uma rotina específica ou virar descanso.',
    example: 'Toque no dia para editar.',
    target: '[data-tutorial="schedule-day"]',
    route: '/schedule',
    placement: 'top',
    optional: true,
    targetLabel: 'Dia',
  }),
  step({
    id: 'schedule-start-today',
    section: 'schedule',
    title: 'Começar treino de hoje',
    description: 'Quando há treino marcado para hoje, você consegue iniciar pela agenda ou pelo Dashboard.',
    example: 'Essa etapa fica segura mesmo se não houver treino marcado.',
    target: '[data-tutorial="schedule-start-today"]',
    route: '/schedule',
    placement: 'top',
    optional: true,
    targetLabel: 'Iniciar',
  }),
]

const progressSteps = [
  step({
    id: 'progress-overview',
    section: 'progress',
    title: 'Visão geral da evolução',
    description: 'Acompanhe volume, frequência, carga e tendências do seu treino.',
    example: 'Quanto mais treinos salvos, mais os gráficos fazem sentido.',
    target: '[data-tutorial="progress-overview"]',
    route: '/progress',
    placement: 'bottom',
    targetLabel: 'Evolução',
  }),
  step({
    id: 'progress-chart',
    section: 'progress',
    title: 'Gráficos',
    description: 'Os gráficos ajudam a enxergar progresso ao longo do tempo.',
    example: 'Use filtros para comparar períodos e exercícios.',
    target: '[data-tutorial="progress-chart"]',
    route: '/progress',
    placement: 'top',
    optional: true,
    targetLabel: 'Gráfico',
  }),
]

const photosRecoverySteps = [
  step({
    id: 'progress-photos',
    section: 'photosRecovery',
    title: 'Fotos de progresso',
    description: 'Registre fotos para comparar evolução visual com segurança.',
    example: 'As preferências de privacidade controlam prévias sensíveis.',
    target: '[data-tutorial="progress-photos"]',
    route: '/progress-photos',
    placement: 'bottom',
    targetLabel: 'Fotos',
  }),
  step({
    id: 'muscle-recovery',
    section: 'photosRecovery',
    title: 'Recuperação muscular',
    description: 'Veja quais grupos estão mais recuperados ou exigem cuidado.',
    example: 'As cores indicam fadiga e recuperação estimada.',
    target: '[data-tutorial="muscle-recovery"]',
    route: '/muscle-recovery',
    placement: 'bottom',
    targetLabel: 'Recuperação',
  }),
]

const nutritionSteps = [
  step({
    id: 'nutrition-water',
    section: 'nutrition',
    title: 'Água do dia',
    description: 'Acompanhe sua meta de hidratação e some ml rapidamente.',
    example: 'A água nunca fica negativa, mesmo removendo registros.',
    target: '[data-tutorial="nutrition-water"]',
    route: '/nutrition',
    placement: 'bottom',
    targetLabel: 'Água',
  }),
  step({
    id: 'nutrition-meals',
    section: 'nutrition',
    title: 'Refeições',
    description: 'Registre refeições para acompanhar calorias, proteína e rotina alimentar.',
    example: 'Use isso como apoio, sem complicar o treino.',
    target: '[data-tutorial="nutrition-meals"]',
    route: '/nutrition',
    placement: 'top',
    optional: true,
    targetLabel: 'Refeições',
  }),
  step({
    id: 'nutrition-history',
    section: 'nutrition',
    title: 'Histórico nutricional',
    description: 'Revise dias anteriores sem misturar registros de datas diferentes.',
    example: 'Ajuda a entender consistência de água e refeições.',
    target: '[data-tutorial="nutrition-history"]',
    route: '/nutrition',
    placement: 'top',
    optional: true,
    targetLabel: 'Histórico',
  }),
]

const notificationsSteps = [
  step({
    id: 'notifications-bell',
    section: 'notifications',
    title: 'Sino no header',
    description: 'O sino abre uma prévia dos alertas mais importantes.',
    example: 'Você também pode abrir a central completa.',
    target: '[data-tutorial="notification-bell"]',
    route: '/',
    placement: 'bottom',
    targetLabel: 'Sino',
  }),
  step({
    id: 'notifications-list',
    section: 'notifications',
    title: 'Central de notificações',
    description: 'Aqui ficam notificações de treino, água, recuperação, metas e preferências.',
    example: 'Arquive o que já resolveu para manter tudo limpo.',
    target: '[data-tutorial="notifications-list"]',
    route: '/notifications',
    placement: 'bottom',
    targetLabel: 'Central',
  }),
  step({
    id: 'notifications-preferences',
    section: 'notifications',
    title: 'Preferências',
    description: 'Ajuste permissões e lembretes sem sair do ForgeFlow.',
    example: 'No Android, algumas permissões dependem do sistema.',
    target: '[data-tutorial="notification-preferences"]',
    route: '/notifications',
    placement: 'top',
    optional: true,
    targetLabel: 'Preferências',
  }),
]

const settingsSteps = [
  step({
    id: 'settings-profile',
    section: 'settings',
    title: 'Perfil e acesso',
    description: 'Revise informações da conta e acesso ao perfil.',
    example: 'Dados técnicos ficam escondidos para não confundir.',
    target: '[data-tutorial="settings-profile"]',
    route: '/settings',
    placement: 'left',
    optional: true,
    targetLabel: 'Perfil',
  }),
  step({
    id: 'settings-theme',
    section: 'settings',
    title: 'Tema claro, escuro ou sistema',
    description: 'Escolha o tema do app sem quebrar cards, inputs ou navegação.',
    example: 'O tutorial também se adapta ao tema escolhido.',
    target: '[data-tutorial="settings-theme"]',
    route: '/settings',
    placement: 'bottom',
    targetLabel: 'Tema',
  }),
  step({
    id: 'settings-accent',
    section: 'settings',
    title: 'Cor principal do app',
    description: 'A accent color muda botões, bordas, brilhos e o spotlight do tutorial.',
    example: 'O destaque visual segue a cor escolhida pelo usuário.',
    target: '[data-tutorial="settings-accent"]',
    route: '/settings',
    placement: 'top',
    targetLabel: 'Accent',
  }),
  step({
    id: 'settings-simple-mode',
    section: 'settings',
    title: 'Experiência simplificada',
    description: 'Preferências de densidade e modo de uso ajudam a deixar o app menos cansativo.',
    example: 'Nenhum recurso precisa ser removido para ficar mais fácil de entender.',
    target: '[data-tutorial="settings-simple-mode"]',
    route: '/settings',
    placement: 'top',
    optional: true,
    targetLabel: 'Experiência',
  }),
  step({
    id: 'settings-tutorial',
    section: 'settings',
    title: 'Tutorial e ajuda',
    description: 'Aqui você continua, reinicia ou revê seções específicas a qualquer momento.',
    example: 'Use “Rever Treino Ativo” para abrir o modo demo de novo.',
    target: '[data-tutorial="settings-tutorial"]',
    route: '/settings',
    placement: 'top',
    targetLabel: 'Tutorial e ajuda',
  }),
]

const goalsSteps = [
  step({
    id: 'goals-overview',
    section: 'goals',
    title: 'Metas',
    description: 'Crie metas simples para acompanhar hábitos, volume, frequência ou progresso.',
    example: 'Escolha poucas metas por vez para não se perder.',
    target: '[data-tutorial="goals-overview"]',
    route: '/goals',
    placement: 'bottom',
    targetLabel: 'Metas',
  }),
]

export const tutorialFlows = {
  welcome: {
    id: 'welcome',
    title: 'Tour inicial do ForgeFlow',
    description: 'Um guia curto pelas áreas mais importantes do app.',
    sections: ['welcome', 'dashboard', 'navigation', 'workout', 'settings'],
    steps: [
      ...welcomeSteps,
      dashboardSteps[0],
      dashboardSteps[2],
      dashboardSteps[3],
      dashboardSteps[4],
      navigationSteps[0],
      navigationSteps[4],
      step({
        id: 'welcome-workout-demo',
        section: 'workout',
        title: 'Quer ver como registrar um treino?',
        description: 'Agora o guia abre um treino teste local para explicar kg, reps, concluir série e finalizar sem salvar dados fake.',
        example: 'Se você já tiver treino real em andamento, o guia explica o treino real sem sobrescrever.',
        route: '/start-workout',
        target: '[data-tutorial="active-workout-header"]',
        placement: 'bottom',
        targetLabel: 'Modo tutorial',
      }),
      workoutSteps[2],
      workoutSteps[4],
      workoutSteps[5],
      workoutSteps[6],
      workoutSteps[10],
      settingsSteps[4],
      step({
        id: 'welcome-finish',
        section: 'welcome',
        title: 'Pronto para treinar',
        description: 'Você já sabe onde começar, como registrar séries e onde rever ajuda.',
        example: 'Finalize agora ou reabra qualquer seção em Configurações.',
        route: '/settings',
        target: '[data-tutorial="settings-tutorial"]',
        placement: 'top',
        targetLabel: 'Rever depois',
      }),
    ],
  },
  dashboard: {
    id: 'dashboard',
    title: 'Tutorial do Dashboard',
    description: tutorialSections.dashboard.description,
    sections: ['dashboard'],
    steps: dashboardSteps,
  },
  navigation: {
    id: 'navigation',
    title: 'Tutorial da navegação',
    description: tutorialSections.navigation.description,
    sections: ['navigation'],
    steps: navigationSteps,
  },
  workouts: {
    id: 'workouts',
    title: 'Tutorial de Treinos',
    description: tutorialSections.workouts.description,
    sections: ['workouts'],
    steps: workoutsSteps,
  },
  workout: {
    id: 'workout',
    title: 'Tutorial do treino ativo',
    description: tutorialSections.workout.description,
    sections: ['workout'],
    steps: workoutSteps,
  },
  exercises: {
    id: 'exercises',
    title: 'Tutorial da biblioteca',
    description: tutorialSections.exercises.description,
    sections: ['exercises'],
    steps: exercisesSteps,
  },
  history: {
    id: 'history',
    title: 'Tutorial do histórico',
    description: tutorialSections.history.description,
    sections: ['history'],
    steps: historySteps,
  },
  schedule: {
    id: 'schedule',
    title: 'Tutorial da agenda',
    description: tutorialSections.schedule.description,
    sections: ['schedule'],
    steps: scheduleSteps,
  },
  progress: {
    id: 'progress',
    title: 'Tutorial da evolução',
    description: tutorialSections.progress.description,
    sections: ['progress'],
    steps: progressSteps,
  },
  photosRecovery: {
    id: 'photosRecovery',
    title: 'Tutorial de fotos e recuperação',
    description: tutorialSections.photosRecovery.description,
    sections: ['photosRecovery'],
    steps: photosRecoverySteps,
  },
  nutrition: {
    id: 'nutrition',
    title: 'Tutorial de nutrição',
    description: tutorialSections.nutrition.description,
    sections: ['nutrition'],
    steps: nutritionSteps,
  },
  notifications: {
    id: 'notifications',
    title: 'Tutorial de notificações',
    description: tutorialSections.notifications.description,
    sections: ['notifications'],
    steps: notificationsSteps,
  },
  profile: {
    id: 'profile',
    title: 'Tutorial do perfil',
    description: 'Veja seus dados, preferências e atalhos da conta.',
    sections: ['settings'],
    steps: [
      step({
        id: 'profile-overview',
        section: 'settings',
        title: 'Perfil',
        description: 'A página de Perfil concentra dados pessoais, experiência do app e preferências do usuário.',
        example: 'Use Configurações para aparência, tutorial e privacidade avançada.',
        target: '[data-tutorial="profile-overview"]',
        route: '/profile',
        placement: 'bottom',
        targetLabel: 'Perfil',
      }),
    ],
  },
  settings: {
    id: 'settings',
    title: 'Tutorial de configurações',
    description: tutorialSections.settings.description,
    sections: ['settings'],
    steps: settingsSteps,
  },
  goals: {
    id: 'goals',
    title: 'Tutorial de metas',
    description: tutorialSections.goals.description,
    sections: ['goals'],
    steps: goalsSteps,
  },
}

export const tutorialSectionOrder = Object.values(tutorialSections)
  .sort((a, b) => a.order - b.order)
  .map((section) => section.id)

export function getFlowForPath(pathname = '/') {
  if (tutorialRouteFlows[pathname]) return tutorialRouteFlows[pathname]

  const match = Object.entries(tutorialRouteFlows).find(([path]) => {
    if (path === '/') return pathname === '/'
    return pathname.startsWith(path)
  })

  return match?.[1] || 'welcome'
}

export function getTutorialFlow(flowId = 'welcome') {
  return tutorialFlows[flowId] || tutorialFlows.welcome
}

export function getTutorialSection(sectionId = '') {
  return tutorialSections[sectionId] || null
}

export function getTutorialSections() {
  return tutorialSectionOrder.map((sectionId) => tutorialSections[sectionId]).filter(Boolean)
}

export function getFlowStepCount(flowId = 'welcome') {
  return getTutorialFlow(flowId).steps.length
}

export function getSectionStepCount(sectionId = '') {
  const flow = tutorialFlows[sectionId]
  if (flow) return flow.steps.length

  return Object.values(tutorialFlows).reduce((total, flowItem) => {
    return total + flowItem.steps.filter((item) => item.section === sectionId).length
  }, 0)
}
